DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS
(
ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
UNIQUE (NAME)
);
CREATE TABLE GENRES
(
ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
UNIQUE (NAME)
);
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    GENRE_ID BIGINT,
    FOREIGN KEY (GENRE_ID)REFERENCES GENRES (ID),
    UNIQUE (NAME, AUTHOR_ID, GENRE_ID)
);
CREATE TABLE COMMENTS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    TEXT      VARCHAR(2000) NOT NULL,
    BOOK_ID BIGINT       NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID)
);