DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    UNIQUE (FIRST_NAME, LAST_NAME)
);
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    UNIQUE (NAME)
);
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    GENRE_ID BIGINT,
    FOREIGN KEY (GENRE_ID)REFERENCES GENRES (ID)
);