INSERT INTO AUTHORS (NAME)
values ('TEST AUTHOR'),
       ('TEST AUTHOR 2');
INSERT INTO GENRES (NAME)
values ('TEST GENRE'),
       ('TEST GENRE 2');

INSERT INTO BOOKS (NAME, AUTHOR_ID, GENRE_ID)
values ('TEST BOOK', 1, 1);
